export const WEAPONS = [
  {
    name: 'Baby Missile',
    damage: 15,
    blastRadius: 8,
    craterDepth: 2,
    ammo: Infinity,
    color: '#fff',
    description: 'Basic projectile. Unlimited ammo.',
    behavior: 'standard',
  },
  {
    name: 'Missile',
    damage: 25,
    blastRadius: 12,
    craterDepth: 3,
    ammo: 10,
    color: '#ff9800',
    description: 'Solid damage and blast radius.',
    behavior: 'standard',
  },
  {
    name: 'Heavy Missile',
    damage: 40,
    blastRadius: 16,
    craterDepth: 5,
    ammo: 5,
    color: '#f44336',
    description: 'Big boom. Big crater.',
    behavior: 'standard',
  },
  {
    name: 'MIRV',
    damage: 12,
    blastRadius: 8,
    craterDepth: 2,
    ammo: 3,
    color: '#e040fb',
    description: 'Splits into 5 warheads at peak altitude.',
    behavior: 'mirv',
    submunitions: 5,
    spreadRadius: 15,
  },
  {
    name: 'Bouncer',
    damage: 20,
    blastRadius: 10,
    craterDepth: 2.5,
    ammo: 5,
    color: '#76ff03',
    description: 'Bounces 3 times before detonating.',
    behavior: 'bouncer',
    bounces: 3,
    bounceFactor: 0.5,
  },
  {
    name: 'Roller',
    damage: 25,
    blastRadius: 10,
    craterDepth: 3,
    ammo: 3,
    color: '#ffeb3b',
    description: 'Rolls along terrain on impact.',
    behavior: 'roller',
    rollDuration: 2.0,
  },
  {
    name: 'Dirt Ball',
    damage: 5,
    blastRadius: 12,
    craterDepth: -6,
    ammo: 5,
    color: '#8d6e63',
    description: 'Adds terrain instead of removing it. Bury your opponent!',
    behavior: 'standard',
  },
  {
    name: 'Tunneler',
    damage: 30,
    blastRadius: 6,
    craterDepth: 8,
    ammo: 2,
    color: '#00bcd4',
    description: 'Burrows through terrain on impact.',
    behavior: 'tunneler',
    tunnelLength: 20,
  },
  {
    name: 'Napalm',
    damage: 8,
    blastRadius: 20,
    craterDepth: 1,
    ammo: 3,
    color: '#ff6f00',
    description: 'Spreads fire over a wide area. Burns for damage.',
    behavior: 'napalm',
    burnDamage: 5,
    burnTicks: 3,
  },
  {
    name: 'Nuke',
    damage: 60,
    blastRadius: 30,
    craterDepth: 10,
    ammo: 1,
    color: '#fff',
    description: 'Massive devastation. Handle with care.',
    behavior: 'nuke',
  },
];

export function getWeaponByName(name) {
  return WEAPONS.find(w => w.name === name);
}
